cloud:
  aws:
    credentials:
      access-key: ENTER_ACCESS_KEY_HERE
      secret-key: ENTER_SECRET_KEY_HERE
    region:
      static: ENTER_REGION_HERE
    stack:
      auto: false

application:
  bucket:
    name: ENTER_BUCKET_NAME_HERE


spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2MB
      max-file-size: 200MB
      max-request-size: 215MB

server:
  port: 8080
